<a href="https://colab.research.google.com/github/Mstfayldz/Data-Science/blob/master/Array_to_DataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [85]:
import numpy as np
#pip install numpy yüklü değilse

# ARRAY

In [86]:
my_list=[10,20,30,40]

In [87]:
np.array(my_list)

array([10, 20, 30, 40])

In [88]:
my_np_array=np.array(my_list)

In [89]:
type(my_np_array)

numpy.ndarray

In [90]:
my_np_array.max()

np.int64(40)

In [91]:
np.ones(5)
#5 tane içinde 1 bulunduran array yazdırır

array([1., 1., 1., 1., 1.])

In [92]:
np.zeros(5)
# 5 tane içinde 0 bulunduran array yazdırır

array([0., 0., 0., 0., 0.])

In [93]:
np.random.random(5)
#random 5 tane sayı barındıran array yazar

array([0.78125541, 0.06704844, 0.87215263, 0.74071841, 0.88082716])

ARRAY ARITMETIC

In [94]:
my_list1=[1,2]

In [95]:
my_list2=[2,3]

In [96]:
my_list1+my_list2

[1, 2, 2, 3]

In [97]:
my_np_array1 = np.array(my_list1)

In [98]:
my_np_array2=np.array(my_list2)

In [99]:
#arraylarda toplama listelerdeki gibi birleştirme şeklinde olmaz her aynı indexe sahip olsan sayılar toplanır

In [100]:
my_np_array1+my_np_array2

array([3, 5])

In [101]:
my_np_array1-my_np_array2

array([-1, -1])

In [102]:
my_np_array1* my_np_array2

array([2, 6])

In [103]:
my_np_array1/my_np_array2

array([0.5       , 0.66666667])

In [104]:
my_list1*5


[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [105]:
my_np_array1*5

array([ 5, 10])

In [106]:
my_np_array3=np.array([10,20,30,40])

BROADCASTİNG==> İşlem yapılacak iki farklı arrayın boyutlarının veya index sayılarının eşit olmadığı durumda yapılacak olan işlemlerdir

In [107]:
#my_np_array3*my_np_array1 hata verir

In [108]:
my_np_array4=np.array([10])

In [109]:
my_np_array3*my_np_array4# tek indexlilerde sorun çıkmaz

array([100, 200, 300, 400])

arange,index

In [110]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [111]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
np_array=np.arange(10)

In [114]:
np_array[0]

np.int64(0)

In [115]:
np_array[-1]

np.int64(9)

In [116]:
np_array[1:3]

array([1, 2])

In [117]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [118]:
np.random.randn(4,4)#4 e 4 dimensionlu matris

array([[-0.02443635,  0.20273577,  0.00477915,  0.15505372],
       [-0.05775321, -0.88979282, -0.04157512,  0.45462884],
       [-1.35443163,  0.64052698,  0.1373978 ,  0.81970625],
       [-0.59419995, -0.02791919, -0.89276569,  1.65328143]])

In [119]:
np.random.randint(1,300,5)# 1-300 arası bana 5 tane random integer ver

array([  5, 184, 281, 133, 149])