<a href="https://colab.research.google.com/github/Mstfayldz/Data-Science/blob/master/Matrix_to_DataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MATRIX

In [215]:
import numpy as np

row*column

In [216]:
my_matrix=[[1,2],[3,4]]

In [217]:
my_matrix

[[1, 2], [3, 4]]

In [218]:
my_matrix[0][1]

2

In [219]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [220]:
np.random.random((4,4))

array([[0.01136854, 0.93066944, 0.20958227, 0.62199464],
       [0.2065832 , 0.91132018, 0.2780135 , 0.75238416],
       [0.66576215, 0.43461042, 0.3895347 , 0.16176711],
       [0.05717917, 0.72365744, 0.85333148, 0.86982553]])

In [221]:
np.random.rand(4,4)

array([[0.09063306, 0.21475757, 0.45672524, 0.47303907],
       [0.01548648, 0.04242737, 0.9934149 , 0.91043087],
       [0.09907368, 0.10228179, 0.32536117, 0.87792365],
       [0.11197354, 0.10909991, 0.39138035, 0.67756964]])

In [222]:
np_matrix=np.array([[5,10],[15,20]])

In [223]:
np_matrix.sum()
#print(np_matrix.sum()) yazılabilir doğrusu da budur

np.int64(50)

MATRIX ARITMETIC

In [224]:
first_array=np.array([[10,20],[30,40]])

In [225]:
second_array=np.array([[5,10],[15,20]])

In [226]:
first_array+second_array

array([[15, 30],
       [45, 60]])

In [227]:
third_array=np.array([[1,2]])

In [228]:
first_array+third_array
#Broadcasting olayı olur row-column yani dimensions olarak aynı olmasalar da tek row olduğu için iki row a da bu tek row eklendi


array([[11, 22],
       [31, 42]])

In [229]:
foutrh_array=np.array([[10,15],[20,25],[30,35]])

In [230]:
#first_array+foutrh_array #broadcasting hatası olur shapeler==>dimensionslar aynı değildir

In [231]:
first_array.shape
# second_array.shape
# third_array.shape          =====>> her zaman (row,column)
# foutrh_array.shape


(2, 2)

MATRIX MULTIPLICATION ==> burada aslında dot product işlemi yapılır ilk matisin rowu ikinci matrisin de columnu alınır ve sonuç matrisinin  sahpe'i böyle belirlenir işlemler içinse ilk arrayın ilk row u ikinci arrayın ilk column u ile çarpılır ve hepsi tek tek toplanır ve sonra ilk elamn olarak yazılır sonra ilk arrayın ilk rowu ikinci arrayın 2. columnuyla aynı şekilde devam eder. Ama ilk arrayın columnu ile ikinci arrayın row değerlerinin de eşit olması gerekir örneğin: 1x3  3x2

In [232]:
multy_array1=np.array([[1,2,3]])

In [233]:
multy_array2=np.array([[4,2],[5,3],[6,4]])

In [234]:
result_matrix=multy_array1.dot(multy_array2)#==> 1*4=4 , 2*5=10 , 3*6=18 => toplamı 32 /// 1*2=2 ,  2*3=6 , 3*4=12 => toplamı 20

In [235]:
result_matrix

array([[32, 20]])

In [236]:
result_matrix.shape

(1, 2)

Numpy Examples

In [237]:
new_array= np.random.randint(1,101,20)

In [238]:
new_array

array([22,  3, 29, 92, 62, 11, 79, 47, 69, 44, 88, 90, 70, 20, 39, 85, 18,
       84, 96, 43])

In [239]:
new_array>25

array([False, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True])

In [240]:
new_array[new_array>25]

array([29, 92, 62, 79, 47, 69, 44, 88, 90, 70, 39, 85, 84, 96, 43])

In [241]:
new_array[new_array%2]

array([22,  3,  3, 22, 22,  3,  3,  3,  3, 22, 22, 22, 22, 22,  3,  3, 22,
       22, 22,  3])

In [242]:
# transpose / reshape ==>transpose: row ve column değerlerini birbriyle değiştiriyor // reshape: kendi atadığımız değerle değiştiriyor

In [243]:
matrix_transpose= np.array([[1,2,3],[4,5,6]])

In [244]:
matrix_transpose

array([[1, 2, 3],
       [4, 5, 6]])

In [245]:
matrix_transpose.T#==> matrix_transpose.transpose() aynı fonksiyon

array([[1, 4],
       [2, 5],
       [3, 6]])

In [246]:
matrix_reshape=np.random.random((6,1))

In [247]:
matrix_reshape

array([[0.83159381],
       [0.48631992],
       [0.08782138],
       [0.80248396],
       [0.16916383],
       [0.56937339]])

In [248]:
matrix_reshape.reshape(2,3)

array([[0.83159381, 0.48631992, 0.08782138],
       [0.80248396, 0.16916383, 0.56937339]])

In [249]:
# Z-SCORES ==> outlier(çıkıntıları tespit etmek için harika bir yöntemdir) (data-mean)/std

In [250]:
data=np.array([10,12,13,14,15,16,17,25,100,101])

In [251]:
mean=data.mean()

In [252]:
mean

np.float64(32.3)

In [253]:
std=data.std()

In [254]:
std

np.float64(34.31049402150893)

In [255]:
z_score=(data-mean)/std

In [256]:
z_score

array([-0.64994692, -0.59165572, -0.56251012, -0.53336451, -0.50421891,
       -0.47507331, -0.44592771, -0.21276289,  1.97315725,  2.00230285])

In [257]:
z_score[z_score>1]

array([1.97315725, 2.00230285])

In [258]:
data[z_score>1]

array([100, 101])

MATH EQUATİONS

In [259]:
# 2x+3y=8 // 5x+7y=19

In [260]:
#coefficent için
A=np.array([[2,3],[5,7]])

In [261]:
# constant için
b=np.array([8,19])

In [262]:
solution= np.linalg.solve(A,b) # bu fonksiyon linear algebra dan gelir

In [263]:
solution

array([1., 2.])